
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
before_deploy:
  - npm install netlify-cli -g
  - yarn build
env:
  - CI=true
deploy:
  provider: script
  script: netlify deploy --dir=dist --prod
  skip_cleanup: true
  on:
    branch: master
