language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
 - yarn install
script:
  - npm test
before_deploy:
  - npm install netlify-cli -g
  - yarn build
env:
  - CI=true
deploy:
  provider: netlify
  site: pranjaljain.tech
  auth: $NETLIFY_ACCESS_TOKEN
  edge: true # opt in to dpl v2
  on:
    branch: master
